# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded


    providers:
        main:
            entity: { class: AppBundle:Users, property: username }

    encoders:
        AppBundle\Entity\Users: bcrypt

    firewalls:
        main:
            pattern: /.*
            form_login:
                check_path: /login
                login_path: /login
                default_target_path: /
#                logout_path: /logout
            logout:
                path:   /logout
                target: /new
            security: true
            anonymous: true

    access_control:
        - { path: /users/new, role: ROLE_ADMIN }
        - { path: /users/.*, role: ROLE_ADMIN }
        - { path: /chat/*, role: ROLE_USER }
        - { path: /login/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /login_check/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /update-count$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /upload-data, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /new/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: /*$, role: ROLE_USER }

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
